### ISSUE TITLE
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)

### ISSUE THREAD

**Issue by saidm00** [Balajanovski/simple-raymarcher#1]
Program received signal SIGSEGV, Segmentation fault.
Scene::sceneSDF (this=<optimized out>, position=...) at /home/said-linux/CLionProjects/simple-raymarcher/Source/Scene.cpp:16
16	        auto minimum_intersection = config_manager_instance.get_object(0)->sdf(position);

**Comment by Balajanovski** [comment]
Commit 525c740b6e05d9ef66fcd0c8d291a5848154a3ca solves it
